"""One ordered live/durable event channel shared by DSH and ASKAI capabilities."""

from __future__ import annotations

import asyncio
from collections import defaultdict
from typing import Any, Awaitable, Callable

from .live_stream import LiveTurnStream
from .projection_writer import DurableProjectionWriter, ProjectionScope
from .repository import KernelEventRepository


ProgressSink = Callable[[dict[str, Any]], Awaitable[None]]


class TurnEventChannel:
    def __init__(
        self,
        *,
        events: KernelEventRepository,
        scope: ProjectionScope,
        live_stream: LiveTurnStream,
    ) -> None:
        self._live_stream = live_stream
        self._writer = DurableProjectionWriter(events=events, scope=scope)
        self._next_stream_seq = 0
        self._lock = asyncio.Lock()
        self._known_actions: set[str] = set()
        self._durable_actions: set[str] = set()
        self._pending: dict[str, list[dict[str, Any]]] = defaultdict(list)
        self._pending_durable: dict[str, list[dict[str, Any]]] = defaultdict(list)
        self._side_history: list[dict[str, Any]] = []
        self._durable_side_event_ids: set[str] = set()
        self._closed = False

    async def publish_kernel(
        self, row: dict[str, Any], *, publish_live: bool = True
    ) -> dict[str, Any]:
        async with self._lock:
            if self._closed:
                return dict(row)
            sequenced = self._sequence(row)
            action_id = self._started_action_id(sequenced)
            if publish_live:
                self._live_stream.publish(sequenced)
            if action_id:
                self._known_actions.add(action_id)
                for pending in self._pending.pop(action_id, []):
                    self._publish_side_locked(pending, action_id=action_id)
            return sequenced

    async def publish_side(self, action_id: str, row: dict[str, Any]) -> None:
        async with self._lock:
            if self._closed:
                return
            if action_id not in self._known_actions:
                self._pending[action_id].append(dict(row))
                return
            self._publish_side_locked(row, action_id=action_id)

    async def publish_standalone(self, row: dict[str, Any]) -> None:
        """Publish an ASKAI-owned item which is not a child of a kernel tool item.

        Approval request IDs are generated by DSH's approval protocol and are
        intentionally different from the model tool-call ID.  Treating approval
        cards as tool progress therefore leaves them queued forever.  Approval
        items are first-class timeline items and can be persisted immediately.
        """
        async with self._lock:
            if self._closed:
                return
            sequenced = self._sequence(row)
            self._side_history.append(sequenced)
            self._live_stream.publish(sequenced)
            self._writer.enqueue(sequenced)
            self._durable_side_event_ids.add(str(sequenced.get("event_id") or ""))

    async def mark_action_durable(self, action_id: str) -> None:
        async with self._lock:
            if self._closed:
                return
            self._durable_actions.add(action_id)
            for row in self._pending_durable.pop(action_id, []):
                self._writer.enqueue(row)
                self._durable_side_event_ids.add(str(row.get("event_id") or ""))

    async def flush(self) -> None:
        await self._writer.flush()

    async def close(self) -> list[dict[str, Any]]:
        async with self._lock:
            # A missing kernel tool-start event must not leak progress into a
            # different item. Such rows are deliberately discarded.
            self._pending.clear()
            self._pending_durable.clear()
            self._closed = True
        await self._writer.close()
        return [
            row for row in self._side_history
            if str(row.get("event_id") or "") in self._durable_side_event_ids
        ]

    async def abort(self) -> None:
        self._pending.clear()
        self._pending_durable.clear()
        await self._writer.abort()

    def _publish_side_locked(self, row: dict[str, Any], *, action_id: str) -> None:
        sequenced = self._sequence(row)
        self._side_history.append(sequenced)
        self._live_stream.publish(sequenced)
        if action_id in self._durable_actions:
            self._writer.enqueue(sequenced)
            self._durable_side_event_ids.add(str(sequenced.get("event_id") or ""))
        else:
            self._pending_durable[action_id].append(sequenced)

    def _sequence(self, row: dict[str, Any]) -> dict[str, Any]:
        self._next_stream_seq += 1
        return {
            **dict(row),
            "stream_seq": self._next_stream_seq,
            "stream_seq_end": self._next_stream_seq,
        }

    @staticmethod
    def _started_action_id(row: dict[str, Any]) -> str:
        if row.get("type") != "item.started" or row.get("item_kind") != "tool":
            return ""
        payload = row.get("payload")
        return str((payload or {}).get("callId") or "") if isinstance(payload, dict) else ""


class TurnEventRegistry:
    def __init__(self, events: KernelEventRepository) -> None:
        self._events = events
        self._channels: dict[str, TurnEventChannel] = {}

    def register(self, scope: ProjectionScope, live_stream: LiveTurnStream) -> None:
        if scope.message_id in self._channels:
            raise RuntimeError(f"turn event channel already exists: {scope.message_id}")
        self._channels[scope.message_id] = TurnEventChannel(
            events=self._events, scope=scope, live_stream=live_stream
        )

    async def publish_kernel(
        self, message_id: str, row: dict[str, Any], *, publish_live: bool = True
    ) -> dict[str, Any]:
        channel = self._channels.get(message_id)
        if channel is None:
            # No channel registered (the runner's failure path after the
            # channel closed): the row still needs a durable per-message
            # ordinal, drawn from the same counter the persistence boundary
            # uses, instead of the kernel-session ordinal it carries.
            seq = (await self._events.reserve_stream_ordinals(
                message_id=message_id, span=1
            ))[0]
            return {**dict(row), "stream_seq": seq, "stream_seq_end": seq}
        return await channel.publish_kernel(row, publish_live=publish_live)

    def progress_sink(self, message_id: str, action_id: str) -> ProgressSink | None:
        channel = self._channels.get(message_id)
        if channel is None or not action_id:
            return None

        async def publish(row: dict[str, Any]) -> None:
            await channel.publish_side(action_id, row)

        return publish

    async def publish_standalone(self, message_id: str, row: dict[str, Any]) -> None:
        channel = self._channels.get(message_id)
        if channel is not None:
            await channel.publish_standalone(row)

    async def finish(self, message_id: str) -> list[dict[str, Any]]:
        channel = self._channels.pop(message_id, None)
        return await channel.close() if channel is not None else []

    async def abort(self, message_id: str) -> None:
        channel = self._channels.pop(message_id, None)
        if channel is not None:
            await channel.abort()

    async def flush(self, message_id: str) -> None:
        channel = self._channels.get(message_id)
        if channel is not None:
            await channel.flush()

    async def mark_action_durable(self, message_id: str, action_id: str) -> None:
        channel = self._channels.get(message_id)
        if channel is not None:
            await channel.mark_action_durable(action_id)
